name: "Publish into FlakeHub"
on:
  push:
    branches:
      - "nyxpkgs-unstable"
  workflow_call:
  workflow_dispatch:

jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@V28
        with:
          extra_nix_config: |
            accept-flake-config = true
            sandbox-fallback = false
          install_options: --daemon
          install_url: https://releases.nixos.org/nix/nix-2.22.3/install
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Update Nix
        run : nix profile install .#nix-flake-schemas_git
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "chaotic-cx/nyx"
          rolling: true
          visibility: "public"
          flakehub-push-branch: "main"
