name: "Publish into FlakeHub"
on:
  push:
    branches:
      - "nyxpkgs-unstable"
  workflow_dispatch:

jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: "chaotic-cx/nyx"
          rolling: true
          visibility: "public"
