name: Bump nixpkgs

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump:
    concurrency:
      group: nyx-main-build
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.bump.outcome == 'success' }}
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: "accept-flake-config = true"
      - uses: actions/checkout@v3
      - name: Update nixpkgs flake
        run: nix flake lock --update-input nixpkgs || exit 1; git diff --exit-code flake.lock && exit 1 || exit 0
        continue-on-error: true
        id: bump
      - name: Commit nixpkgs bump
        if: steps.bump.outcome == 'success'
        run: |
          set -e
          git config --global user.name 'Chaotic Github Actions'
          git config --global user.email 'actions@chaotic.cx'
          git add flake.lock
          git commit -m "nixpkgs: bump to $(date +%Y%m%d)"
          git push
  build:
    needs: bump
    if: needs.bump.outputs.success == 'true'
    uses: ./.github/workflows/build.yml
    secrets: inherit
