name: Bump nixpkgs

on:
  # Trigger this workflow every day at midnight
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: nixpkgs-bump

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.bump.outcome == 'success' }}
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: "accept-flake-config = true"
      - uses: actions/checkout@v3
      - name: Update nixpkgs flake
        run: nix flake lock --update-input nixpkgs || exit 1; git diff --exit-code flake.lock && exit 1 || exit 0
        continue-on-error: true
        id: bump
      - name: Commit nixpkgs bump
        if: steps.bump.outcome == 'success'
        run: |
          set -e
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@chaotic.cx'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add flake.lock
          git commit -m "nixpkgs: bump to $(date +%Y%m%d)"
          git push
